### ISSUE TITLE
 Search function does not work in the list view

### ISSUE THREAD

**Issue by sasakitat** [hifive/hifive-pitalium-explorer#11]
2ページ目以降に移動してから検索ボタンを押すと検索が行われているが、
1ページ目で検索ボタンを押しても検索が行われない。

**Comment by meganetaaan** [comment]
1ページ目で検索ボタンを押す→日付をクリックしてスクリーンショット一覧を表示
の順番で操作すると、検索で絞りこまれた結果だけが表示されました。

検索より先にスクリーンショット一覧を表示した場合、表示済みの要素に対しては検索が効かないようです。
