### ISSUE TITLE
Filepersisiter devides results at the same time into different testClasses.

### ISSUE THREAD

**Issue by meganetaaan** [hifive/hifive-pitalium-explorer#15]
Filepersisiterを使う際、同じタイミングで取得したテスト結果が、
異なるテストクラス毎に分かれて表示されてしまいます。
スクリーンショットを添付します。
![filepersister](https://cloud.githubusercontent.com/assets/1918755/8843861/4a09a8e8-3149-11e5-9a87-530209c98d32.PNG)
例えば2015_07_23_11_41_33のテストでは3つのテストクラスを同時に実行しましたが、そのクラス毎に結果が分かれています。

**Comment by sasakitat** [comment]
比較画面で期待値の画像が取得できないケースが見られました。
ですので、早期の修正が必要です。

**Comment by sasakitat** [comment]
佐々木が提起した問題については、
別のissueを切りなおしました。
https://github.com/hifive/hifive-pitalium-explorer/issues/16

**Comment by tkashi** [comment]
テストクラスを列で表示するように変更してください
