### ISSUE TITLE
テスト結果ディレクトリを画面上で移動したい場合の方法について

### ISSUE THREAD

**Issue by jjcall0904** [hifive/hifive-pitalium-explorer#60]
http://localhost:8080/pitalium-explorer/list.html
にアクセスすると、pitalium-explorer\WEB-INF\classespersisterConfig.json
に設定したディレクトリ以下が表示されますが、このディレクトリ以下にさらにディレクトリを
複数作成してそれぞれにcurrentExpectedIds.jsonを配置したいのですが
簡単に実現する方法はありますでしょうか？

**Comment by tkashi** [comment]
@jjcall0904 さん

ご回答が遅くなり大変申し訳ありません。

残念ながら、上記のような複数フォルダの結果を表示する機能を現在は有していません。
要望として、本件対応したいと思います。

**Comment by jjcall0904** [comment]
返信ありがとうございます。

質問の背景を簡単に記載します。

現在、サイトを複数のグループに分割しそれぞれに「SET_EXPECTED、RUN_TEST」を指定して
サイト別・グループ別にテスト結果を取得するというリグレッションテストツールを作成しております。※pitaliumは触らないというポリシー

出力先フォルダ構成は以下のようなイメージです。
C:\pitalium\results\site01\testgroup01\
　　2017_01_30_17_38_11
　　2017_02_30_17_38_11　　･･･
C:\pitalium\results\\site01\testgroup02\
　　2017_01_30_17_38_11
　　2017_02_30_17_38_11　　･･･

上記を実現するためにサイト別・グループ別にpersisterConfig.jsonを置換え→pitaliumを起動という動作を繰り返すバッチファイルを作成しております。

そうなると、テスト結果を見る段階になってpitalium-explorerにてディレクトリの切替ができないので
方法としては以下の2つの検討となってしまっております。

①ランチャーを作成して、pitalium-explorerのpersisterConfig.jsonをおきかえつつ
　tomcatを再起動してブラウザを起動させる

②pitalium-explorer.war自体をサイト別・グループ別に作成してURLを切り替える

①②ともに「何をしてるんだろう？？？」と自分自身思っているのですが
「pitaliumは触らない」から進んでおりますので困っているという次第です。

本件への対応をお待ちしております。

**Comment by tkashi** [comment]
explorerPersisterConfig.jsonを作成し、以下の形式で記述することで、
リスト画面の左上のメニューからディレクトリを変更できるようにしました。

```
{
	"files": {
		"results1": {
			"resultDirectory": "pitalium-results1"
		},
		"results2": {
			"resultDirectory": "pitalium-results2"
		}
	},
	"defaultResultKey": "results1"
}

```

filesオブジェクト内の各値のオブジェクトの形式は、今までのpersisterConfig.jsonのfileに記述した形式と同じです。
defaultResultKeyを指定した場合、最初の画面では指定したフォルダの結果を表示します。指定がない場合はランダムに表示されます。

このファイルの作成は必須ではなく、今までの形式でpersisterConfig.jsonで指定することも可能です（後方互換性の担保）。
