### ISSUE TITLE
一部のHTMLファイルが読み込むJavaScriptファイルのパスが正しくない

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium-explorer#68]
- diff.htmlが読み込むbootstrapが3.3.6ではなく3.3.5なので読み込めない
- list.htmlが読み込むhifiveライブラリがh5.jsではなくh5.dev.jsなので読み込めない

**Comment by meganetaaan** [comment]
devブランチ最新版で確認。

- bootstrap->v3.3.6
- hifive->h5.js

を使うように修正する。
