### ISSUE TITLE
テストの書き方が間違っている

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium-explorer#77]
whenの引数にmockでない値を与えている。
以下のテストメソッドで間違った記述をしている。
- ImageControllerTest#testGetImageOK
- ImageControllerTest#testGetProcessedEdgeColorIndex0
- ImageControllerTest#testGetProcessedEdgeColorIndex1
- ImageControllerTest#testGetDiffImageOkDifferent
- ImageControllerTest#testGetDiffImageOk

**Comment by ishikawa1027** [comment]
修正完了
