### ISSUE TITLE
新しくなったpitaliumのAPIにテストが追従していない

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium-explorer#80]
mockが現行では使用していないメソッドについて書かれている。
以下のテストメソッドで古い記述をしている。
- ApiControllerTest#testListTestExecution
- ApiControllerTest#testListTestExecutionWithPageSize
- ApiControllerTest#testListTestExecutionWithPageSizeUnlimited
- ApiControllerTest#testSearch
- ApiControllerTest#testListScreenshot
- ApiControllerTest#testGetDetail

**Comment by tkmHashi** [comment]
ImageControllerTest#○○ErrorのテストについてもprivateなExplorerServiceがもつprivateなPersisterServiceのメソッドの戻り値を操作しなければテストができない。
テスト側ではprivateなExplorerServiceは呼び出せないので○○Errorのテストは行えない。

**Comment by ishikawa1027** [comment]
修正完了
