### ISSUE TITLE
エラーのポリシーが統一されていない

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium-explorer#86]
#76, #78, #79, #81のテストで想定されているエラーと実際のエラーが異なっている

#76, #78, #79, #81を個別に対応しようとすると他のissueと実行結果が食い違ってしまう

スクリーンショット画像を取得または差分画像を生成するときの各例外ケースについて、どのエラーコードを返すか決める

**Comment by meganetaaan** [comment]
#76, #78, #79, #81について
* 実行結果やスクリーンショットのファイルが存在しない場合のみNOT_FOUND
* その他発生した例外は全てINTERNAL_SERVER_ERROR
をAPIとして返す。
